---
- name: disable password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: "sshd -t -f %s"
  notify: restart ssh
- name: disable remote root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    validate: "sshd -t -f %s"
  notify: restart ssh
# TODO optionally switch port