---
terraform_download_url: https://releases.hashicorp.com/terraform/0.14.8/terraform_0.14.8_linux_amd64.zip
packer_download_url: https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
vagrant_download_url: https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_linux_amd64.zip
gcloud_download_url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-311.0.0-linux-x86_64.tar.gz
aws_download_url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
step_cli_download_url: https://github.com/smallstep/cli/releases/download/v0.15.12/step-cli_0.15.12_amd64.deb
go_download_url: https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
bat_download_url: https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb
lsd_download_url: https://github.com/Peltoche/lsd/releases/download/0.17.0/lsd_0.17.0_amd64.deb
lazygit_download_url: https://github.com/jesseduffield/lazygit/releases/download/v0.26.1/lazygit_0.26.1_Linux_x86_64.tar.gz
pyenv_download_url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
nvm_download_url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
sdkman_download_url: "https://get.sdkman.io?rcupdate=false"
leiningen_download_url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
