---
- name: Install Python
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Make Python 3 default
  block:
  - name: Remove symlink to Python 2
    file:
      path: /usr/bin/python
      state: absent
  - name: Create symlink for Python 3
    file:
      state: link
      src: /usr/bin/python3
      dest: /usr/bin/python
      owner: root
      group: root
      mode: '777'

- name: Check Pyenv installation
  stat:
    path: "/home/{{ user.name }}/.pyenv"
  register: stat_pyenv

- name: Install pyenv
  shell: curl -L {{ pyenv_download_url }} | bash
  become: no
  when: not stat_pyenv.stat.exists

- name: Check NVM installation
  stat:
    path: "/home/{{ user.name }}/.nvm"
  register: stat_nvm

- name: Install nvm
  shell: curl -o- {{ nvm_download_url }} | bash
  become: no
  when: not stat_nvm.stat.exists

- name: Check SDKman installation
  stat:
    path: "/home/{{ user.name }}/.sdkman"
  register: stat_sdkman

- name: Install SDKman
  shell: curl -s {{ sdkman_download_url }} | bash
  become: no
  when: not stat_sdkman.stat.exists

- name: Check Leiningen existence
  stat:
    path: "/home/{{ user.name }}/bin/lein"
  register: stat_lein

- name: Install Leiningen
  get_url:
    url: "{{ leiningen_download_url }}"
    dest: "/home/{{ user.name }}/bin"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "760"
  when: not stat_lein.stat.exists

- name: Install PHP
  apt:
    name: php
    state: present

#- name: Install Java
#  apt:
#    name: default-jdk
#    state: present

- name: Check Go installation
  stat:
    path: /usr/local/bin/go
  register: stat_go

- name: Install Go
  block:
    - name: Download Go installer
      get_url:
        url: "{{ go_download_url }}"
        dest: /tmp/
      register: go_download
    - name: Unpack Go installer
      unarchive:
        src: "{{ go_download.dest }}"
        dest: /opt/
        remote_src: yes
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
    - name: Remove installer
      file:
        path: "{{ go_download.dest }}"
        state: absent
    - name: Create link to Go
      file:
        src: /opt/go/bin/go
        dest: /usr/local/bin/go
        state: link
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
    - name: Create link to Gofmt
      file:
        src: /opt/go/bin/gofmt
        dest: /usr/local/bin/gofmt
        state: link
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
  when: not stat_go.stat.exists
