---
# tasks file for customization
- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: install base software
  apt:
    name:
    - whois
    - nmap
    - build-essential
    - zsh
    - ansible
    - shellcheck
    - tree
    - htop
    - tmux
    - ripgrep
    - fd-find
    - jq
    - unzip
    - vim
    - git
    - curl
    - wget
    - openssl
    - openvpn
    - ranger
    state: present

- include_tasks: hashicorp.yml
- include_tasks: cloud.yml
